application: tellthewizard
module: api
version: 0-0-0
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: .*
  script: app.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.1"